version: '3'

services:
  userdb:
    container_name: userdb
    build: ./app/user/database
    ports:
      - "5432:5432"

  user:
    container_name: user
    image: user
    build: ./app/user/flask
    ports:
      - "81:81"
    environment:
      - DATABASE_URL=postgresql://postgres:password@userdb:5432/usermanagement
      - FLASK_APP=user
    depends_on:
      - userdb
  
  user_grpc:
    container_name: user_grpc
    image: user_grpc
    build: ./app/user/grpc_service
    environment:
      - DATABASE_URL=postgresql://postgres:password@userdb:5432/usermanagement

volumes:
  pgdata: {}