version: '3'

services:
  userdb:
    container_name: userdb
    build: ./app/user/database
    ports:
      - "5432:5432"
      
  user:
    container_name: user
    image: user
    build: ./app/user/
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql://postgres:password@userdb:5432/usermanagement
      - FLASK_APP=user
    depends_on:
      - userdb

  #cars:
    #container_name: cars
    #image: cars
    #build: ./app/cars/
    #ports:
    #  - "70:70"
    #environment:
    #  - FLASK_APP=cars

  recommendations:
    container_name: recommendations
    image: recommendations
    build: ./app/recommendations/
    ports:
      - 90:90
    environment:
      - USER_HOST: user
      # CARS_HOST: cars

volumes:
  pgdata: {}