version: '3'

services:
  db:
    container_name: db
    build: ./app/user/database
    ports:
      - "5432:5432"
      
  pythonapp:
    container_name: pythonapp
    image: pythonapp
    build: ./app/user/app
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/usermanagement
      - FLASK_APP=user
    depends_on:
      - db


volumes:
  pgdata: {}