# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import car_pb2 as car__pb2


class CarStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CarId = channel.unary_unary(
                '/Car/CarId',
                request_serializer=car__pb2.CarRequest.SerializeToString,
                response_deserializer=car__pb2.CarIdResponse.FromString,
                )
        self.Car = channel.unary_unary(
                '/Car/Car',
                request_serializer=car__pb2.CarRequest.SerializeToString,
                response_deserializer=car__pb2.CarData.FromString,
                )


class CarServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CarId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Car(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CarServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CarId': grpc.unary_unary_rpc_method_handler(
                    servicer.CarId,
                    request_deserializer=car__pb2.CarRequest.FromString,
                    response_serializer=car__pb2.CarIdResponse.SerializeToString,
            ),
            'Car': grpc.unary_unary_rpc_method_handler(
                    servicer.Car,
                    request_deserializer=car__pb2.CarRequest.FromString,
                    response_serializer=car__pb2.CarData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Car', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Car(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CarId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Car/CarId',
            car__pb2.CarRequest.SerializeToString,
            car__pb2.CarIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Car(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Car/Car',
            car__pb2.CarRequest.SerializeToString,
            car__pb2.CarData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
