# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: car.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tcar.proto\"\xf6\x01\n\nCarRequest\x12\x13\n\x06\x63\x61r_id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x13\n\x06region\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x12\n\x05price\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12\x11\n\x04year\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x19\n\x0cmanufacturer\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x12\n\x05model\x18\x06 \x01(\tH\x05\x88\x01\x01\x12\x16\n\tcondition\x18\x07 \x01(\tH\x06\x88\x01\x01\x42\t\n\x07_car_idB\t\n\x07_regionB\x08\n\x06_priceB\x07\n\x05_yearB\x0f\n\r_manufacturerB\x08\n\x06_modelB\x0c\n\n_condition\"(\n\x0b\x43\x61rDataList\x12\x19\n\x04\x63\x61rs\x18\x01 \x03(\x0b\x32\x0b.CarRequest\"\x1e\n\x0c\x43\x61rRequestID\x12\x0e\n\x06\x63\x61r_id\x18\x01 \x01(\x05\",\n\x0f\x43\x61rDataResponse\x12\x19\n\x04\x63\x61rs\x18\x01 \x01(\x0b\x32\x0b.CarRequest\"\'\n\x15SearchByRegionRequest\x12\x0e\n\x06region\x18\x01 \x01(\t\"%\n\x14SearchByModelRequest\x12\r\n\x05model\x18\x01 \x01(\t\"3\n\x1bSearchByManufacturerRequest\x12\x14\n\x0cmanufacturer\x18\x01 \x01(\t\"#\n\x13SearchByYearRequest\x12\x0c\n\x04year\x18\x01 \x01(\t\"-\n\x18SearchByConditionRequest\x12\x11\n\tcondition\x18\x01 \x01(\t2\xab\x03\n\x03\x43\x61r\x12,\n\tCarSearch\x12\r.CarRequestID\x1a\x10.CarDataResponse\x12\'\n\nGetCarData\x12\x0b.CarRequest\x1a\x0c.CarDataList\x12)\n\nSearchById\x12\r.CarRequestID\x1a\x0c.CarDataList\x12\x42\n\x14SearchByManufacturer\x12\x1c.SearchByManufacturerRequest\x1a\x0c.CarDataList\x12<\n\x11SearchByCondition\x12\x19.SearchByConditionRequest\x1a\x0c.CarDataList\x12\x32\n\x0cSearchByYear\x12\x14.SearchByYearRequest\x1a\x0c.CarDataList\x12\x34\n\rSearchByModel\x12\x15.SearchByModelRequest\x1a\x0c.CarDataList\x12\x36\n\x0eSearchByRegion\x12\x16.SearchByRegionRequest\x1a\x0c.CarDataListb\x06proto3')



_CARREQUEST = DESCRIPTOR.message_types_by_name['CarRequest']
_CARDATALIST = DESCRIPTOR.message_types_by_name['CarDataList']
_CARREQUESTID = DESCRIPTOR.message_types_by_name['CarRequestID']
_CARDATARESPONSE = DESCRIPTOR.message_types_by_name['CarDataResponse']
_SEARCHBYREGIONREQUEST = DESCRIPTOR.message_types_by_name['SearchByRegionRequest']
_SEARCHBYMODELREQUEST = DESCRIPTOR.message_types_by_name['SearchByModelRequest']
_SEARCHBYMANUFACTURERREQUEST = DESCRIPTOR.message_types_by_name['SearchByManufacturerRequest']
_SEARCHBYYEARREQUEST = DESCRIPTOR.message_types_by_name['SearchByYearRequest']
_SEARCHBYCONDITIONREQUEST = DESCRIPTOR.message_types_by_name['SearchByConditionRequest']
CarRequest = _reflection.GeneratedProtocolMessageType('CarRequest', (_message.Message,), {
  'DESCRIPTOR' : _CARREQUEST,
  '__module__' : 'car_pb2'
  # @@protoc_insertion_point(class_scope:CarRequest)
  })
_sym_db.RegisterMessage(CarRequest)

CarDataList = _reflection.GeneratedProtocolMessageType('CarDataList', (_message.Message,), {
  'DESCRIPTOR' : _CARDATALIST,
  '__module__' : 'car_pb2'
  # @@protoc_insertion_point(class_scope:CarDataList)
  })
_sym_db.RegisterMessage(CarDataList)

CarRequestID = _reflection.GeneratedProtocolMessageType('CarRequestID', (_message.Message,), {
  'DESCRIPTOR' : _CARREQUESTID,
  '__module__' : 'car_pb2'
  # @@protoc_insertion_point(class_scope:CarRequestID)
  })
_sym_db.RegisterMessage(CarRequestID)

CarDataResponse = _reflection.GeneratedProtocolMessageType('CarDataResponse', (_message.Message,), {
  'DESCRIPTOR' : _CARDATARESPONSE,
  '__module__' : 'car_pb2'
  # @@protoc_insertion_point(class_scope:CarDataResponse)
  })
_sym_db.RegisterMessage(CarDataResponse)

SearchByRegionRequest = _reflection.GeneratedProtocolMessageType('SearchByRegionRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHBYREGIONREQUEST,
  '__module__' : 'car_pb2'
  # @@protoc_insertion_point(class_scope:SearchByRegionRequest)
  })
_sym_db.RegisterMessage(SearchByRegionRequest)

SearchByModelRequest = _reflection.GeneratedProtocolMessageType('SearchByModelRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHBYMODELREQUEST,
  '__module__' : 'car_pb2'
  # @@protoc_insertion_point(class_scope:SearchByModelRequest)
  })
_sym_db.RegisterMessage(SearchByModelRequest)

SearchByManufacturerRequest = _reflection.GeneratedProtocolMessageType('SearchByManufacturerRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHBYMANUFACTURERREQUEST,
  '__module__' : 'car_pb2'
  # @@protoc_insertion_point(class_scope:SearchByManufacturerRequest)
  })
_sym_db.RegisterMessage(SearchByManufacturerRequest)

SearchByYearRequest = _reflection.GeneratedProtocolMessageType('SearchByYearRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHBYYEARREQUEST,
  '__module__' : 'car_pb2'
  # @@protoc_insertion_point(class_scope:SearchByYearRequest)
  })
_sym_db.RegisterMessage(SearchByYearRequest)

SearchByConditionRequest = _reflection.GeneratedProtocolMessageType('SearchByConditionRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHBYCONDITIONREQUEST,
  '__module__' : 'car_pb2'
  # @@protoc_insertion_point(class_scope:SearchByConditionRequest)
  })
_sym_db.RegisterMessage(SearchByConditionRequest)

_CAR = DESCRIPTOR.services_by_name['Car']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CARREQUEST._serialized_start=14
  _CARREQUEST._serialized_end=260
  _CARDATALIST._serialized_start=262
  _CARDATALIST._serialized_end=302
  _CARREQUESTID._serialized_start=304
  _CARREQUESTID._serialized_end=334
  _CARDATARESPONSE._serialized_start=336
  _CARDATARESPONSE._serialized_end=380
  _SEARCHBYREGIONREQUEST._serialized_start=382
  _SEARCHBYREGIONREQUEST._serialized_end=421
  _SEARCHBYMODELREQUEST._serialized_start=423
  _SEARCHBYMODELREQUEST._serialized_end=460
  _SEARCHBYMANUFACTURERREQUEST._serialized_start=462
  _SEARCHBYMANUFACTURERREQUEST._serialized_end=513
  _SEARCHBYYEARREQUEST._serialized_start=515
  _SEARCHBYYEARREQUEST._serialized_end=550
  _SEARCHBYCONDITIONREQUEST._serialized_start=552
  _SEARCHBYCONDITIONREQUEST._serialized_end=597
  _CAR._serialized_start=600
  _CAR._serialized_end=1027
# @@protoc_insertion_point(module_scope)
