# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"\x1e\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"\xbc\x01\n\x0fUserPreferences\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06region\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\t\x12\x0c\n\x04year\x18\x04 \x01(\t\x12\x14\n\x0cmanufacturer\x18\x05 \x01(\t\x12\r\n\x05model\x18\x06 \x01(\t\x12\x11\n\tcondition\x18\x07 \x01(\t\x12\x0c\n\x04\x66uel\x18\x08 \x01(\t\x12\x14\n\x0ctransmission\x18\t \x01(\t\x12\x14\n\x0cposting_date\x18\n \x01(\t\"@\n\x17UserPreferencesResponse\x12%\n\x0bpreferences\x18\x01 \x01(\x0b\x32\x10.UserPreferences2>\n\x05Users\x12\x35\n\x0bPreferences\x12\x0c.UserRequest\x1a\x18.UserPreferencesResponseb\x06proto3')



_USERREQUEST = DESCRIPTOR.message_types_by_name['UserRequest']
_USERPREFERENCES = DESCRIPTOR.message_types_by_name['UserPreferences']
_USERPREFERENCESRESPONSE = DESCRIPTOR.message_types_by_name['UserPreferencesResponse']
UserRequest = _reflection.GeneratedProtocolMessageType('UserRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:UserRequest)
  })
_sym_db.RegisterMessage(UserRequest)

UserPreferences = _reflection.GeneratedProtocolMessageType('UserPreferences', (_message.Message,), {
  'DESCRIPTOR' : _USERPREFERENCES,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:UserPreferences)
  })
_sym_db.RegisterMessage(UserPreferences)

UserPreferencesResponse = _reflection.GeneratedProtocolMessageType('UserPreferencesResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERPREFERENCESRESPONSE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:UserPreferencesResponse)
  })
_sym_db.RegisterMessage(UserPreferencesResponse)

_USERS = DESCRIPTOR.services_by_name['Users']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERREQUEST._serialized_start=14
  _USERREQUEST._serialized_end=44
  _USERPREFERENCES._serialized_start=47
  _USERPREFERENCES._serialized_end=235
  _USERPREFERENCESRESPONSE._serialized_start=237
  _USERPREFERENCESRESPONSE._serialized_end=301
  _USERS._serialized_start=303
  _USERS._serialized_end=365
# @@protoc_insertion_point(module_scope)
